version: 1
formatters:
  defaultFormatter:
    format: '[%(asctime)s][%(levelname)s][%(name)s][%(funcName)s()] %(message)s'
handlers:
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: defaultFormatter
    filename: ext://nl2sql.log_file
    when: D
    interval: 1
    backupCount: 10
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: defaultFormatter
    stream: ext://sys.stdout
loggers:
  nl2sql:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  pgvector_handler:
    level: INFO
    handlers: [console, file]
    propagate: no
root:
  level: INFO
  handlers: [console]